In [9]:
pip install -U evaluate

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: evaluate in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (0.4.6)
Requirement already satisfied: datasets>=2.0.0 in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from evaluate) (4.8.4)
Requirement already satisfied: numpy>=1.17 in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from evaluate) (2.4.3)
Requirement already satisfied: dill in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from evaluate) (0.4.1)
Requirement already satisfied: pandas in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from evaluate) (2.3.3)
Requirement already satisfied: requests>=2.19.0 in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from evaluate) (2.32.5)
Requirement already satisfied: tqdm>=4.62.1 in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from evaluate) (4.67.3)
Requirement already satisfied: xxhash in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from evaluate) (0.70.19)
Requirement already satisfied: fsspec>=2021.05.0 in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from fsspec[http]>=2021.05.0->evaluate) (2026.2.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from evaluate) (1.7.2)
Requirement already satisfied: packaging in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from evaluate) (26.0)
Requirement already satisfied: filelock in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from datasets>=2.0.0->evaluate) (3.25.2)
Requirement already satisfied: pyarrow>=21.0.0 in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from datasets>=2.0.0->evaluate) (23.0.1)
Requirement already satisfied: httpx<1.0.0 in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from datasets>=2.0.0->evaluate) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.3)
Requirement already satisfied: anyio in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (4.12.1)
Requirement already satisfied: certifi in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (2026.2.25)
Requirement already satisfied: httpcore==1.* in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (1.0.9)
Requirement already satisfied: idna in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (3.11)
Requirement already satisfied: h11>=0.16 in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from httpcore==1.*->httpx<1.0.0->datasets>=2.0.0->evaluate) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from huggingface-hub>=0.7.0->evaluate) (1.4.2)
Requirement already satisfied: typer in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from huggingface-hub>=0.7.0->evaluate) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.23.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from requests>=2.19.0->evaluate) (3.4.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from requests>=2.19.0->evaluate) (2.6.3)
Requirement already satisfied: colorama in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from tqdm>=4.62.1->evaluate) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from pandas->evaluate) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from pandas->evaluate) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Requirement already satisfied: click>=8.2.1 in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from typer->huggingface-hub>=0.7.0->evaluate) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from typer->huggingface-hub>=0.7.0->evaluate) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from typer->huggingface-hub>=0.7.0->evaluate) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from typer->huggingface-hub>=0.7.0->evaluate) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in C:\Users\saini\AppData\Roaming\Python\Python314\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [10]:
import pandas as pd
import numpy as np
import torch
import evaluate
import torch.nn as nn
from sklearn.model_selection import train_test_split
from datasets import Dataset
from transformers import pipeline , DataCollatorWithPadding  , AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer

C:\Users\saini\AppData\Roaming\Python\Python314\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [11]:
data = pd.read_csv('D:/Machine Learning/DeepLearing Projects/news_dataset.csv')  
data.head()

,title,text,subject,date,label
0,WATCH: Trump Just Told All The Anti-Gay Bigot...,A whole lot of evangelical Trump voters just d...,News,"November 13, 2016",0
1,"China backs U.N. call for justice in Yemen, U....",GENEVA (Reuters) - China signaled on Wednesday...,worldnews,"September 13, 2017",1
2,THE PEOPLE’S PRESIDENT: Trump Meets With Coal ...,,politics,"Feb 16, 2017",0
3,WSJ REPORTER RIPS INTO DEM CANDIDATES For Thei...,THE WSJ S MARY KISSEL NAILS IT ON THE DEM DEBA...,politics,"Nov 15, 2015",0
4,Lawmakers aim to delay U.S. ceding control of ...,WASHINGTON (Reuters) - Critics of a plan for t...,politicsNews,"September 13, 2016",1

In [12]:
data.shape

(6000, 5)

In [13]:
data.isnull().sum()  # null values in the dataset

title      0
text       0
subject    0
date       0
label      0
dtype: int64

In [14]:
# Full text of the text and title
data['full_text'] = data['title'] + ' ' + data['text']

In [15]:
data.head()

,title,text,subject,date,label,full_text
0,WATCH: Trump Just Told All The Anti-Gay Bigot...,A whole lot of evangelical Trump voters just d...,News,"November 13, 2016",0,WATCH: Trump Just Told All The Anti-Gay Bigot...
1,"China backs U.N. call for justice in Yemen, U....",GENEVA (Reuters) - China signaled on Wednesday...,worldnews,"September 13, 2017",1,"China backs U.N. call for justice in Yemen, U...."
2,THE PEOPLE’S PRESIDENT: Trump Meets With Coal ...,,politics,"Feb 16, 2017",0,THE PEOPLE’S PRESIDENT: Trump Meets With Coal ...
3,WSJ REPORTER RIPS INTO DEM CANDIDATES For Thei...,THE WSJ S MARY KISSEL NAILS IT ON THE DEM DEBA...,politics,"Nov 15, 2015",0,WSJ REPORTER RIPS INTO DEM CANDIDATES For Thei...
4,Lawmakers aim to delay U.S. ceding control of ...,WASHINGTON (Reuters) - Critics of a plan for t...,politicsNews,"September 13, 2016",1,Lawmakers aim to delay U.S. ceding control of ...

In [16]:
data.drop(columns=  ['title', 'text' , "subject" , "date"], axis=1, inplace=True)

In [17]:
data

      label                                          full_text
0         0   WATCH: Trump Just Told All The Anti-Gay Bigot...
1         1  China backs U.N. call for justice in Yemen, U....
2         0  THE PEOPLE’S PRESIDENT: Trump Meets With Coal ...
3         0  WSJ REPORTER RIPS INTO DEM CANDIDATES For Thei...
4         1  Lawmakers aim to delay U.S. ceding control of ...
...     ...                                                ...
5995      1  Exiled Venezuelan opposition magistrates resur...
5996      1  Plague outbreak in Madagascar kills 20: WHO NA...
5997      1  Trump to visit Asia in November, North Korea i...
5998      1  Melania Trump calls taped comments by Donald T...
5999      0  #BoycottPenzeys: HATEFUL, DIVISIVE Penzeys Spi...

[6000 rows x 2 columns]

In [18]:
tarin , test = train_test_split(data  , random_state=11)
tarin.shape , test.shape

((4500, 2), (1500, 2))

In [19]:
x = data.drop(columns=['label' , 'full_text'])
y = data['label']

In [20]:
x_train , x_test , y_train , y_test = train_test_split(x , y , random_state=11)
x_train.shape , x_test.shape , y_train.shape , y_test.shape

((4500, 0), (1500, 0), (4500,), (1500,))

In [21]:
train_dataset = Dataset.from_pandas(tarin , preserve_index=False)
test_dataset = Dataset.from_pandas(test , preserve_index=False)

In [22]:
print(train_dataset)
print(test_dataset)

Dataset({
    features: ['label', 'full_text'],
    num_rows: 4500
})
Dataset({
    features: ['label', 'full_text'],
    num_rows: 1500
})

In [23]:
model_name = 'distilbert/distilbert-base-uncased-finetuned-sst-2-english'

In [24]:
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name , num_labels=2,
    ignore_mismatched_sizes=True)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 104/104 [00:00<00:00, 3565.33it/s]

In [25]:
def preprocessing(dataset):


    
    def tokenize_data(item):
        return tokenizer(item["full_text"] , truncation=True)
    encoded_data =  dataset.map(tokenize_data , batched=True)

    encoded_data.set_format("torch" , columns=["input_ids", "attention_mask", "label"])
    return encoded_data

preprocessing(train_dataset)

Map:   0%|          | 0/4500 [00:00<?, ? examples/s]

Map: 100%|██████████| 4500/4500 [00:02<00:00, 1943.06 examples/s]

Dataset({
    features: ['label', 'full_text', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 4500
})

In [26]:
train_encoded = preprocessing(train_dataset)
test_encoded = preprocessing(test_dataset)

Map:   0%|          | 0/4500 [00:00<?, ? examples/s]

Map: 100%|██████████| 4500/4500 [00:02<00:00, 1781.32 examples/s]
Map: 100%|██████████| 1500/1500 [00:00<00:00, 1530.35 examples/s]

In [27]:
metric = evaluate.combine(["accuracy", "f1", "precision", "recall"])

Downloading builder script: 4.20kB [00:00, 1.70MB/s]
Downloading builder script: 6.79kB [00:00, 3.60MB/s]
Downloading builder script: 7.56kB [00:00, 2.07MB/s]
Downloading builder script: 7.38kB [00:00, 3.78MB/s]

In [28]:
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(predictions=predictions, references=labels)
training_args = TrainingArguments(
    output_dir="./fake_news_model",
    eval_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=4,         
    per_device_eval_batch_size=4,          
    gradient_accumulation_steps=4,       
    fp16=True,                           
    num_train_epochs=3,
    weight_decay=0.01,
    save_strategy="epoch"
)

In [ ]:
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)
trainer = Trainer(
    model = model,
    args = training_args,
    train_dataset=train_encoded,
    eval_dataset = test_encoded,
    data_collator=data_collator,
    compute_metrics=compute_metrics
)
trainer.train()

C:\Users\saini\AppData\Roaming\Python\Python314\site-packages\torch\utils\data\dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

In [ ]:
model.save_pretrained("./fake_news_model")
tokenizer.save_pretrained("./fake_news_model")

In [ ]:
classifier = pipeline("text-classification", model="./fake_news_model", tokenizer="./fake_news_model")